site_name: Ars Post Faber
site_url: https://mydomain.org/mysite
repo_url: https://github.com/jmuozan/ArsPostFaber
repo_name: jmuozan/ArsPostFaber

# Custom logo and favicon
theme:
  name: material
  # Add logo and favicon configuration
  logo: icons/logo.svg
  favicon: icons/logo.svg
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    # Light mode
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: black  # Keep header black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  # Font configuration
  font:
    text: Open Sans
    code: Ubuntu Mono

# Include your custom CSS
extra_css:
  - stylesheets/extra.css

# Add JavaScript to handle sidebar hiding on index page
extra_javascript:
  - javascripts/hide-sidebar.js

# Footer configuration
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://jmuozan.github.io/docs/
      name: Website
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jorgemunozzanon/
      name: LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jorgemunyozz
      name: Twitter
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/jmuozan
      name: Instagram
    - icon: fontawesome/brands/github
      link: https://github.com/jmuozan
      name: GitHub

# Copyright text
copyright: >
  Copyright &copy; 2025 Jorge Muñoz Zanón - 
  Licensed under <a href="https://github.com/jmuozan/ArsPostFaber/blob/main/LICENSE">MIT</a>

plugins:
  - search
  - blog

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums_style: pymdownx-inline

nav:
  - Home: index.md
  - How to use:
    - Bits to Atoms: howto/bits2atoms.md
  - About: 
    - About the Author: about/about.md
    - Childhood: about/childhood.md
  - Contribute: 
    - Project Contribution: contribute/contribute_project.md
    - Documentation Contribution: contribute/contribute_web.md