site_name: Ars Post Faber
site_url: https://mydomain.org/mysite

# Custom logo and favicon
theme:
  name: material
  logo: Icons/ascii_output.png
  favicon: Icons/ascii_output.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    # Light mode
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: black  # Keep header black
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # Font configuration
  font:
    text: Open Sans
    code: Ubuntu Mono

# Include your custom CSS
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - blog

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline

nav:
  - Home: index.md
  - About: 
    - About Me: about/about.md
    - Childhood: about/childhood.md